version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "9701:9701"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9700:80"
    depends_on:
      - fastapi

