services:

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9700:80"
    depends_on:
      - fastapi

  fastapi:
    build: .
    ports:
      - "9701:9701"
